### ISSUE TITLE
THE CONTAINER FAILED DURING INSTALL AND VERIFICATION

### ISSUE THREAD

**Issue by Willy030125** [Questandachievement7Developer/UnifiedContainer#12]
![Screenshot_2020-04-06-14-27-52-859_com termux](https://user-images.githubusercontent.com/59504241/78960999-061ab080-7b1a-11ea-99ff-06dcbdbdad76.jpg)
![Screenshot_2020-04-06-14-30-41-801_com termux](https://user-images.githubusercontent.com/59504241/78961008-0e72eb80-7b1a-11ea-949d-46d1f37ad654.jpg)

**Comment by Questandachievement7Developer** [comment]
okie!

**Comment by Questandachievement7Developer** [comment]
Problem has been resolved! It caused by aosp (or in this case MIUI) libc is diffrent between samsung own oneUI implementation of libraries caused the tar to deny %n on android

resolved by using a static binary solution such as busybox instead
