### ISSUE TITLE
sudo problems when installing RTE-Port_Native

### ISSUE THREAD

**Issue by Willy030125** [Questandachievement7Developer/UnifiedContainer#7]
![Screenshot (247)](https://user-images.githubusercontent.com/59504241/76418094-9b6a3e00-63d0-11ea-984c-851fcafa5d76.png)
![Screenshot (248)](https://user-images.githubusercontent.com/59504241/76418104-9e652e80-63d0-11ea-8100-51623b4addf4.png)

**Comment by Questandachievement7Developer** [comment]
This is a problem is that we are aware of we can try to implement a fix which is emulate sudo with su -c in setup time so the next patch might need a default container renewal
```
sudofix=${folder}/bin/sudo
##### SUDO FIX ####
cat > "$sudofix" <<- EOM
#!/bin/sh
echo "Emulated Sudo revision 1"
su -c "\$@"
EOM
chmod +x ${folder}/bin/sudo
```
