### ISSUE TITLE
Error loop: possibly missing firmware for module (empires-container)

### ISSUE THREAD

**Issue by Willy030125** [Questandachievement7Developer/UnifiedContainer#8]
![Screenshot_20200313-231638_Termux](https://user-images.githubusercontent.com/59504241/76670358-a684c000-65c2-11ea-843a-94bf54dadb5a.jpg)
![Screenshot_20200313-231937_Termux](https://user-images.githubusercontent.com/59504241/76670362-abe20a80-65c2-11ea-8139-9d641cbb977b.jpg)

**Comment by Questandachievement7Developer** [comment]
This looping problem only occurs when default container is installing 
What architechture do you use currently?

**Comment by Willy030125** [comment]
arm64-v8a

**Comment by Questandachievement7Developer** [comment]
Missing kernel module are normal here however we do note this as a future update fix because kernel module compilation are unecessary upon installation time
